# Saving and Loading Data

<b>Functions in this section:</b> np.loadtxt(), np.nanmean(), np.nan_to_num(), np.save_txt(), np.save(), np.load(), np.savez()

In [ ]:
import numpy as np

# Reading txt file

In [45]:
data = np.loadtxt("data.txt", delimiter = ",")

In [46]:
data

array([1., 2., 8., 9., 5., 1., 2., 8., 9., 5., 1., 2., 8., 9., 5., 1., 2.,
       8., 9., 5., 1., 2., 8., 9., 5.])

In [47]:
data.mean()

5.0

## CSV Files

In [89]:
rain_data = np.loadtxt("data_csv.csv", delimiter=",")

In [90]:
rain_data

array([[ 1.,  2.,  8.,  9.],
       [nan,  5.,  1.,  2.],
       [ 8.,  9.,  5.,  1.],
       [ 8.,  9., nan,  5.],
       [ 1.,  2.,  8.,  9.],
       [ 5.,  1.,  2.,  8.],
       [ 9.,  5.,  2.,  5.]])

In [91]:
np.isnan(rain_data).any()

True

# Saving txt files

In [100]:
total_mean = np.nanmean(rain_data)

In [101]:
np.nan_to_num(rain_data, nan=total_mean, copy=False)

array([[1., 2., 8., 9.],
       [5., 5., 1., 2.],
       [8., 9., 5., 1.],
       [8., 9., 5., 5.],
       [1., 2., 8., 9.],
       [5., 1., 2., 8.],
       [9., 5., 2., 5.]])

In [98]:
rain_data

array([[1., 2., 8., 9.],
       [5., 5., 1., 2.],
       [8., 9., 5., 1.],
       [8., 9., 5., 5.],
       [1., 2., 8., 9.],
       [5., 1., 2., 8.],
       [9., 5., 2., 5.]])

In [109]:
np.savetxt("new_data.csv", rain_data, delimiter=",")

In [110]:
np.savetxt("new_data.csv", rain_data, delimiter=",", fmt="%.0f")

In [111]:
np.savetxt("new_data.csv", rain_data, delimiter=",", fmt="%.0f", header="Rain Data")

# Loading and Saving Numpy objects 

In [112]:
daily_mean = rain_data.mean(axis = 1)

In [113]:
daily_mean

array([5.  , 3.25, 5.75, 6.75, 5.  , 4.  , 5.25])

In [114]:
np.save("daily_mean", daily_mean)

In [143]:
np.load("daily_mean.npy")

array([5.  , 3.25, 5.75, 6.75, 5.  , 4.  , 5.25])

## Saving several numpy objects at once

In [120]:
np.savez("rainy_days", rain_data, daily_mean)

In [129]:
np.load("rainy_days.npz").files

['arr_0', 'arr_1']

In [130]:
np.load("rainy_days.npz")["arr_0"]

array([[1., 2., 8., 9.],
       [5., 5., 1., 2.],
       [8., 9., 5., 1.],
       [8., 9., 5., 5.],
       [1., 2., 8., 9.],
       [5., 1., 2., 8.],
       [9., 5., 2., 5.]])

In [131]:
np.load("rainy_days.npz")["arr_1"]

array([5.  , 3.25, 5.75, 6.75, 5.  , 4.  , 5.25])

In [139]:
np.savez("rainy_days", rain_data=rain_data, daily_mean=daily_mean)

In [140]:
np.load("rainy_days.npz").files

['rain_data', 'daily_mean']

In [141]:
np.load("rainy_days.npz")["daily_mean"]

array([5.  , 3.25, 5.75, 6.75, 5.  , 4.  , 5.25])

In [144]:
type(np.load("rainy_days.npz"))

numpy.lib.npyio.NpzFile