# Making and Modifying Matrices
<b>Functions and attributes:</b> np.array, .tolist(), .ndim, .dtype, .size, .shape, np.newaxis(), .reshape(), .flatten(), .copy(), .all(), .any(), np.nan, np.isnan()

In [1]:
# Importing the NumPy Package
import numpy as np

## Making a Matrix / 2D-array
Can be viewed as a list of lists.

In [2]:
# Making a Matrix
my_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
my_first_matrix = np.array(my_list)
my_first_matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Going back to a list
#### Vectors

In [3]:
# Going back from a 1D-array
vect = np.arange(5)
list(vect)

[0, 1, 2, 3, 4]

#### Matrices

In [4]:
# Not exactly what we want
list(my_first_matrix)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [5]:
# The right way to go back to lists
back_to_list = my_first_matrix.tolist()

In [6]:
back_to_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

### Accessing Values

In [7]:
my_first_matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### Accessing Rows

In [8]:
# Accessing the first row
my_first_matrix[0]

array([1, 2, 3])

In [9]:
# Changing a row
my_first_matrix[3] = np.array([2, 3, 2])
my_first_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 3, 2]])

#### Accessing a coordinate

In [10]:
# Accessing a single entry, the long way...
my_first_matrix[2][1]

8

In [11]:
# The easy way of accessing values
my_first_matrix[2, 1]

8

In [12]:
# Changing values
my_first_matrix[2, 1] = 100
my_first_matrix

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7, 100,   9],
       [  2,   3,   2]])

#### Accessing Columns

In [13]:
# Accessing the second columns
my_first_matrix[:, 1]

array([  2,   5, 100,   3])

## Attributes of a Matrix 

#### .ndim
Gives out the dimension.

In [14]:
my_first_matrix

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7, 100,   9],
       [  2,   3,   2]])

In [15]:
my_first_matrix.ndim

2

In [16]:
vector = np.arange(4)

In [17]:
vector.ndim

1

#### .dtype
All entries in a matrix need to have the same type! 

In [18]:
my_first_matrix.dtype

dtype('int32')

#### .size
Gives out how many entries in total. Is given by the number of rows times the number of columns.

In [19]:
my_first_matrix

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7, 100,   9],
       [  2,   3,   2]])

In [20]:
my_first_matrix.size

12

#### .shape
The most important attribute on matrices! Gives you out a tuple with (rows, columns). 

<i>Comment:</i> Tuples are like a list; however, we cannot be modified.

In [21]:
my_first_matrix

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7, 100,   9],
       [  2,   3,   2]])

In [22]:
my_first_matrix.shape

(4, 3)

In [23]:
vector

array([0, 1, 2, 3])

In [24]:
vector.shape

(4,)

#### Going from 1-D to 2-D arrays

In [25]:
column_vec = vector[:, np.newaxis]
column_vec

array([[0],
       [1],
       [2],
       [3]])

In [26]:
column_vec.shape

(4, 1)

In [27]:
row_vec = vector[np.newaxis, :]
row_vec

array([[0, 1, 2, 3]])

In [28]:
row_vec.shape

(1, 4)

## Changing the Shape

### .reshape()
Make a 10x10 matrix with entries from 1 to 100

In [29]:
# Vector from 1 to 100
vector = np.arange(1, 101)
vector

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [30]:
# Reshape into a 10 by 10 matrix/2D-array
hundred_matrix = vector.reshape(10, 10)
hundred_matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [31]:
# Reshape creates a view
hundred_matrix[0, 0] = -20
vector

array([-20,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [32]:
# Can go back to vector with reshape
back_to_vector = hundred_matrix.reshape(100)
back_to_vector

array([-20,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [33]:
# The lazy way of creating matrices with 20 rows
twenty_five = hundred_matrix.reshape(20, -1)
twenty_five

array([[-20,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [34]:
# You cannot reshape a matrix into any shape
prime = hundred_matrix.reshape(23,-1)

ValueError: cannot reshape array of size 100 into shape (23,newaxis)

### Difference between reshape and flatten

In [35]:
# Reshape creates a view
hundred_matrix.reshape(-1)

array([-20,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

#### .flatten()
Makes a copy.

In [36]:
hundred_matrix

array([[-20,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [37]:
new_vector = hundred_matrix.flatten()

In [38]:
new_vector

array([-20,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [39]:
new_vector[1] = -1
new_vector

array([-20,  -1,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [40]:
hundred_matrix

array([[-20,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

#### How to force a copy

In [41]:
copy_matrix = np.copy(hundred_matrix.reshape(25, -1))

## New Matrices and specifying axes in functions

### Creating vectors and matrices with only ones and zeros

In [42]:
# Making matrices with only zeros
np.zeros((3, 7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [43]:
# Making matrices with only ones
np.ones((8, 14))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [44]:
# Works also for vectors
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

#### Identity Matrix

In [45]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Specifying Axis of Aggregate Functions

In [46]:
matrix = np.array([[7, 8, 7, 3], [4, 5, 2, 3], [0, 4, 3, 4]])
matrix

array([[7, 8, 7, 3],
       [4, 5, 2, 3],
       [0, 4, 3, 4]])

#### The sum function

In [47]:
matrix.sum()

50

In [48]:
matrix.sum(axis=0)

array([11, 17, 12, 10])

In [49]:
matrix.sum(axis=1)

array([25, 14, 11])

<i>Comment:</i> The axis you specify is the one that disipares!

#### The mean function

In [50]:
matrix.mean()

4.166666666666667

In [51]:
matrix.mean(axis=0)

array([3.66666667, 5.66666667, 4.        , 3.33333333])

In [52]:
matrix.mean(axis=1)

array([6.25, 3.5 , 2.75])

## Boolean Vectors and Matrices

In [53]:
vector = np.array([True, False, True, True])
vector

array([ True, False,  True,  True])

In [54]:
vector.dtype

dtype('bool')

In [55]:
matrix = vector.reshape(2, -1)
matrix

array([[ True, False],
       [ True,  True]])

### How to get Boolean matrices?

In [56]:
matrix = np.arange(10).reshape(2, 5)
matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
bool_matrix = matrix < 5
bool_matrix

array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False]])

### Any and All
All - Are all the entries True?

Any - Are any of the entries True?

In [58]:
bool_matrix

array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False]])

In [59]:
bool_matrix.all()

False

In [60]:
bool_matrix.any()

True

In [61]:
bool_matrix.all(axis=0)

array([False, False, False, False, False])

In [62]:
bool_matrix.all(axis=1)

array([ True, False])

In [63]:
bool_matrix.any(axis=0)

array([ True,  True,  True,  True,  True])

In [64]:
bool_matrix.any(axis=1)

array([ True, False])

### What is np.nan?
Sometimes you are missing some data. They are set to np.nan.

In [65]:
np.nan

nan

In [66]:
rain = np.array([[1, 3, 5], [2, 3, np.nan]])
rain

array([[ 1.,  3.,  5.],
       [ 2.,  3., nan]])

In [67]:
# Are there nan values?
np.isnan(rain)

array([[False, False, False],
       [False, False,  True]])