# 07 Exercise Solution - Basic Linear Algebra

This exercise set is all about doing standard linear algebra exercises using NumPy. 

In [2]:
#DON'T MODIFY THIS CELL, ONLY RUN IT.

# Importing NumPy as np.
import numpy as np

## Exercise 1: Import the Linalg Submodule

In [3]:
# Importing the linalg submodule from NumPy
from numpy import linalg

## Exercise 2: Simple Vector Operations

### Exercise 2a: 
Are any of the vectors $[1, 2, 3]$  and $[2, 3, 4]$  parallel? What about orthogonal?

In [4]:
# Make the vectors
vec_1 = np.arange(1, 4)
vec_2 = np.arange(2, 5)

# Checking if parallel
print(f"The cross product between is {np.cross(vec_1, vec_2)}")

# Checking if orthogonal
print(f"The inner product is {np.dot(vec_1, vec_2)}")

The cross product between is [-1  2 -1]
The inner product is 20


<i>Conclusion:</i> No, the vectors are neither parallel nor orthogonal.

### Exercise 2b: 
Can you find the angle between the vector $[1, 2, 3]$ and $[2, 3, 4]$?

In [5]:
# Defining the angle function
def angle(vect_1, vect_2):
    cos_angle = np.dot(vect_1, vect_2)/(linalg.norm(vect_1) * linalg.norm(vect_2))
    return np.around(np.arccos(cos_angle), 4)

# Finding the angle
print(f"The angle is {angle(vec_1, vec_2)}")

The angle is 0.1219


## Exercise 3: Simple Matrix Operations

Define the matrices 
$$ A= 
\begin{bmatrix}
1&1&2\\
1&1&1\\
1&1&1
\end{bmatrix}\quad \text{and}\quad B= 
\begin{bmatrix}
1&0&0\\
0&1&-2\\
0&0&1
\end{bmatrix}.
$$

### Exercise 3a: 
Find the matrix product $AB$.

In [6]:
# Defining the matrices
A = np.ones((3, 3))
A[0, 2] = 2

B = np.eye(3)
B[1, 2] = -2

# Finding the matrix product AB
A @ B

array([[ 1.,  1.,  0.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])

### Exercise 3b: 
Find the matrix product $B^{-1}A^5$.

In [7]:
# Find the matrix power
linalg.inv(B) @ linalg.matrix_power(A, 5)

array([[142., 142., 185.],
       [327., 327., 426.],
       [109., 109., 142.]])

### Exercise 3c: 
Find the transpose of $A$, namely $A^T$. Compute the product $A A^T$.

In [8]:
# Finding the transpose of $A$
print(f"The transpose\n{A.T}\n")

# Finding the product of $AA^T$
print(f"The product\n{A @ A.T}")

The transpose
[[1. 1. 1.]
 [1. 1. 1.]
 [2. 1. 1.]]

The product
[[6. 4. 4.]
 [4. 3. 3.]
 [4. 3. 3.]]


## Exercise 4: Balancing Chemical Equations

In this exercise we are going to use NumPy to balance a set of chemical equations. The question is how to balance the equation
$$x*C_4H_{10}+y*O_2 = v*H_2O + w*CO_2.$$
Written as vectors this becomes
$$x*[4,10,0]+y*[0,0,2]=z*[0,2,1] + w*[1,0,2],$$
or equivalently,
$$
\begin{bmatrix}
4&0&0\\
10&0&-2\\
0&2&-1
\end{bmatrix}
\begin{bmatrix}
x\\ y\\ z
\end{bmatrix} 
=w*\begin{bmatrix}
1\\ 0\\ 2
\end{bmatrix}.
$$

### Exercise 4a: 
Find out if the matrix is invertible.

In [9]:
# Checking if the matrix is invertible
chem_mat = np.array([[4, 0, 0], [10, 0, -2], [0, 2, -1]])
linalg.det(chem_mat) # Since it is nonzero, the matrix is invertible.

16.000000000000007

### Exercise 4b: 
Solve the linear system with $w=1$.

In [10]:
# Finding a solution
solution = linalg.solve(chem_mat, np.array([1, 0, 2]))
print("The solution is: ", solution)

The solution is:  [0.25  1.625 1.25 ]


### Exercise 4c: 
Having 0.25 of a carbon atom doesn’t really make sense. Multiply the vector with the whole numbers from 1 to 10 to see when the solution consists of only whole numbers.

In [11]:
# Print out the multiples from 1 to 10
for i in range(1, 11):
    print(f"The solution multiplied with {i} is {i*solution}")

The solution multiplied with 1 is [0.25  1.625 1.25 ]
The solution multiplied with 2 is [0.5  3.25 2.5 ]
The solution multiplied with 3 is [0.75  4.875 3.75 ]
The solution multiplied with 4 is [1.  6.5 5. ]
The solution multiplied with 5 is [1.25  8.125 6.25 ]
The solution multiplied with 6 is [1.5  9.75 7.5 ]
The solution multiplied with 7 is [ 1.75  11.375  8.75 ]
The solution multiplied with 8 is [ 2. 13. 10.]
The solution multiplied with 9 is [ 2.25  14.625 11.25 ]
The solution multiplied with 10 is [ 2.5  16.25 12.5 ]


### Exercise 4d: 
Write up the balanced equation, in other words, what is $x,$ $y,$ $z,$ and $w$?

$$2*C_4H_{10}+13*O_2 = 10*H_2O + 8*CO_2.$$

## Moral of the Story

NumPy's linear algebra module makes working with linear algebra easy. In many universities around the world, NumPy is used in courses for linear algebra. In Exercise 4 above, you saw that one can use NumPy to balance chemical equations. Many other applications of linear algebra exist and you can check out the article: https://medium.com/@jeremyjkun/here-s-just-a-fraction-of-what-you-can-do-with-linear-algebra-633383d4153f for more examples!