# Basic Linear Algebra

<b>Functions used in this sheet:</b> np.dot, np.cross, from numpy import linalg, linalg.norm, @, linalg.matrix_power(), .T, linalg.det(), linalg.inv(), linalg.solve()

In [1]:
import numpy as np

In [2]:
# The vectors we are going to use in this module.
first_vector = np.array([1, 2, 4])
second_vector = np.array([2, -1, 9])

In [3]:
# The matrices we are going to use in this module.
first_matrix = np.array([[1, 2, 0], [3, 10, -2], [-3, 5, 3]])
second_matrix = np.array([[1, 2, 0], [0, 0, -2], [-3, 8, 3]])

## Linear Algebra for Vectors

<b>Vector Addition<b>
    $$[1, 2, 4]+[2, -1, 9]= [3, 1, 13]$$


In [4]:
first_vector + second_vector

array([ 3,  1, 13])

<b>Matrix Addition<b>
    $$
    \begin{bmatrix}
    1&2&0\\
    3&10&-2\\
    -3&5&3
    \end{bmatrix}
    +
    \begin{bmatrix}
    1&2&0\\
    0&0&-2\\
    -3&8&3
    \end{bmatrix}
    =
    \begin{bmatrix}
    2&4&0\\
    3&10&-4\\
    -6&13&6
    \end{bmatrix}
    $$

In [5]:
first_matrix + second_matrix

array([[ 2,  4,  0],
       [ 3, 10, -4],
       [-6, 13,  6]])

<b>Vector Subtraction<b>
    $$[1, 2, 4]-[2, -1, 9]= [-1, 3, -5]$$

In [6]:
first_vector - second_vector

array([-1,  3, -5])

<b>Matrix Subtraction<b>
        $$
    \begin{bmatrix}
    1&2&0\\
    3&10&-2\\
    -3&5&3
    \end{bmatrix}
    -
    \begin{bmatrix}
    1&2&0\\
    0&0&-2\\
    -3&8&3
    \end{bmatrix}
    =
    \begin{bmatrix}
    0&0&0\\
    3&10&0\\
    0&-3&0
    \end{bmatrix}
    $$

In [7]:
first_matrix - second_matrix

array([[ 0,  0,  0],
       [ 3, 10,  0],
       [ 0, -3,  0]])

<b>Scalar Multiplication Vector<b>
    $$2*[1, 2, 4] = [2, 4, 8]$$

In [8]:
2 * first_vector

array([2, 4, 8])

<b>Scalar Multiplication Matrix<b>
    $$2*    \begin{bmatrix}
    1&2&0\\
    3&10&-2\\
    -3&5&3
    \end{bmatrix} =     \begin{bmatrix}
    2&4&0\\
    6&20&-4\\
    -6&10&6
    \end{bmatrix}$$

In [9]:
2 * first_matrix

array([[ 2,  4,  0],
       [ 6, 20, -4],
       [-6, 10,  6]])

<b>Dot Product<b>

In [10]:
np.dot(first_vector, second_vector)

36

In [11]:
def are_orthogonal(vect1, vect2):
    return np.dot(vect1, vect2) == 0

In [12]:
are_orthogonal(first_vector, second_vector)

False

## Cross Product and Length

<b>Cross Product</b>

In [13]:
np.cross(first_vector, second_vector)

array([22, -1, -5])

In [14]:
np.cross(np.arange(2), np.arange(1,3))

array(-1)

Examples

In [15]:
cross = np.cross(first_vector, second_vector)

In [16]:
np.dot(first_vector, cross)

0

In [17]:
np.dot(second_vector, cross)

0

<b>To do more complex linear algebra we need the linear algebra library.<b>

In [18]:
from numpy import linalg

<b>Length of a Vector<b>

In [19]:
linalg.norm(first_vector)

4.58257569495584

In [20]:
linalg.norm(second_vector)

9.273618495495704

In [21]:
linalg.norm(first_matrix)

12.68857754044952

#### Example

In [22]:
def angle(vect1, vect2):
    cos_angle = np.dot(vect1, vect2)/(linalg.norm(vect1) * linalg.norm(vect2))
    return np.arccos(cos_angle)

In [23]:
angle(first_vector, second_vector)

0.5602591049467772

## Matrix Operation

<b>Pointwise Matrix Multiplication<b>
        $$
    \begin{bmatrix}
    1&2&0\\
    3&10&-2\\
    -3&5&3
    \end{bmatrix}
    *
    \begin{bmatrix}
    1&2&0\\
    0&0&-2\\
    -3&8&3
    \end{bmatrix}
    =
    \begin{bmatrix}
    1&4&0\\
    0&0&4\\
    9&40&9
    \end{bmatrix}
    $$

In [24]:
first_matrix * second_matrix

array([[ 1,  4,  0],
       [ 0,  0,  4],
       [ 9, 40,  9]])

<b>Matrix Product</b>

In [25]:
first_matrix @ first_vector

array([ 5, 15, 19])

In [26]:
first_matrix @ second_matrix

array([[  1,   2,  -4],
       [  9, -10, -26],
       [-12,  18,  -1]])

In [27]:
np.matmul(first_matrix, second_matrix)

array([[  1,   2,  -4],
       [  9, -10, -26],
       [-12,  18,  -1]])

<b>Identity Matrix</b>

In [28]:
np.eye(3) @ first_matrix

array([[ 1.,  2.,  0.],
       [ 3., 10., -2.],
       [-3.,  5.,  3.]])

In [29]:
np.eye(3) @ first_vector

array([1., 2., 4.])

<b> Matrix Power</b>

In [30]:
first_matrix @ first_matrix @ first_matrix @ first_matrix

array([[  895,  2030,  -596],
       [ 3939,  8540, -2626],
       [ 2319,  5671, -1545]])

In [31]:
linalg.matrix_power(first_matrix, 4)

array([[  895,  2030,  -596],
       [ 3939,  8540, -2626],
       [ 2319,  5671, -1545]])

<b>Transpose</b>

In [32]:
first_matrix

array([[ 1,  2,  0],
       [ 3, 10, -2],
       [-3,  5,  3]])

In [33]:
first_matrix.T

array([[ 1,  3, -3],
       [ 2, 10,  5],
       [ 0, -2,  3]])

In [34]:
first_matrix.transpose()

array([[ 1,  3, -3],
       [ 2, 10,  5],
       [ 0, -2,  3]])

## Solving Linear Systems

<b>Matrix Determinant</b>

In [35]:
linalg.det(first_matrix)

33.99999999999999

In [36]:
linalg.det(second_matrix)

28.00000000000001

In [37]:
non_invertible = np.array([[1, 2, 0], [-2, 10, 3], [-3, 8, 3]])

In [38]:
np.around(linalg.det(non_invertible), 10)

0.0

<b>Inverse Matrices</b>

In [39]:
np.around(linalg.inv(first_matrix) @ first_matrix, 10)

array([[ 1.,  0., -0.],
       [-0.,  1.,  0.],
       [-0., -0.,  1.]])

In [40]:
linalg.inv(non_invertible)

array([[ 1.93011413e+15, -1.93011413e+15,  1.93011413e+15],
       [-9.65057063e+14,  9.65057063e+14, -9.65057063e+14],
       [ 4.50359963e+15, -4.50359963e+15,  4.50359963e+15]])

<b>Solving Linear Systems</b>

Problem which have one unique solution.

In [41]:
linalg.solve(first_matrix, first_vector)

array([0.35294118, 0.32352941, 1.14705882])

In [42]:
first_matrix @ linalg.solve(first_matrix, first_vector)

array([1., 2., 4.])

Problem with no solutions.

In [43]:
linalg.solve(non_invertible, first_vector)

array([ 5.79034238e+15, -2.89517119e+15,  1.35107989e+16])

In [44]:
non_invertible @ linalg.solve(non_invertible, first_vector)

array([1., 0., 0.])

Problem with infinitely many solutions.

In [45]:
third_vector = np.array([1, -2, -3])

In [46]:
linalg.solve(non_invertible, third_vector)

array([ 1.32142857, -0.16071429,  0.75      ])

In [47]:
non_invertible @ linalg.solve(non_invertible, third_vector)

array([ 1., -2., -3.])