# Advanced Linear Algebra

In [2]:
import numpy as np
from numpy import linalg

### Finding Eigenvalues and Eigenvectors

In [3]:
# Lets us start with a random matrix
rng = np.random.default_rng()
matrix = rng.random(9).reshape(3, 3)

In [4]:
eigenvalues, eigenvectors = linalg.eig(matrix)

In [5]:
print(eigenvalues)

[ 1.39755571 -0.30412228  0.33542111]


In [6]:
print(eigenvectors)

[[ 0.66654238 -0.117047    0.53331633]
 [ 0.47064658  0.70290112 -0.84564677]
 [ 0.57811162 -0.70159106  0.02133606]]


In [7]:
# Product of the eigenvalues are the determinant!
print("This is the determinant: ", linalg.det(matrix))
print("\nThis is also the determinant: ", np.prod(eigenvalues))

This is the determinant:  -0.14256330688235516

This is also the determinant:  -0.14256330688235502


### Types of Matricies

#### Diagonal Matricies

In [8]:
# A matrix D is diagonal if the only non-zero entries are on the diagonal
D = np.array([[1, 0], [0, 7]])
print(D)

[[1 0]
 [0 7]]


In [9]:
# Stine has shown you the identity matrix
identity = np.eye(3)
print("Identity Matrix:\n", identity, "\n\n")

# We can also make diagonal matricies with the diag-function.
print("Diagonal Matrix:\n", np.diag([1, 7]))

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 


Diagonal Matrix:
 [[1 0]
 [0 7]]


#### Orthogonal Matricies

In [10]:
# A matrix is orthogonal if the columns are orthogonal and each column has length one.
Q = np.array([[1/(2 ** (1/2)), 1/(2 ** (1/2))], [1/(2 ** (1/2)), -1/(2 ** (1/2))]])
print(Q)

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


In [11]:
# Check that Q is orthogonal
print("The columns are orthogonal: ", np.dot(Q[:, 0], Q[:, 1]))
print("The first column has length one: ", linalg.norm(Q[:, 0]))
print("The second column has length one: ", linalg.norm(Q[:, 1]))

The columns are orthogonal:  0.0
The first column has length one:  0.9999999999999999
The second column has length one:  0.9999999999999999


In [14]:
# Orthogonal matricies satisfies Q^(-1) = Q^(T).
# Orthogonal matricies have determinant -1 or 1.
# If we have a system of equations Qx = y, then the solution is x = Q^(-1)y = Q^(T)y

y = np.array([3, 4])

x = Q.T @ y
print(linalg.det(Q))

-0.9999999999999998


#### Upper Triangular Matricies

In [15]:
# Have zeros below the diagonal.
R = np.array([[1, 2], [0, 3]])
print(R)

[[1 2]
 [0 3]]


In [16]:
# Determinant of R is just the product of the diagonal elements.
linalg.det(R)

# Linear systems Rx = y are much faster to solve than general Ax = y systems

3.0000000000000004

### QR Decomposition

In [ ]:
# Every matrix A can be written as A = QR (matrix product) where Q is orthogonal and R is upper triangular.
A = np.array([[1, 2], [3, 4]])
print("QR Decomposition:\n ", linalg.qr(A))

Q_part, R_part = linalg.qr(A)

In [ ]:
print("Orthogonal Matrix:\n", Q_part, "\n\n")
print("Upper Trigangular Part:\n", R_part)

# if A == Q_part @ R_part:
#    print("A is indeed equal to Q_part * R_part")

if np.allclose(A, Q_part @ R_part):
    print("A is indeed equal to Q_part * R_part")

### When systems of equations are not solvable?

In [17]:
A = np.array([[1, 1], [1, 1]])

y = np.array([3, 5])

# Get generic linear algebra exception (or nonsense!)
# x = linalg.solve(A, y)

In [ ]:
# How to fail-safe the code
from numpy.linalg import LinAlgError

try:
    x = linalg.solve(A, y)
    if not np.allclose(A @ x, y):
        raise LinAlgError
    print("The solution is given by x = ", x)
except LinAlgError:
    print("The solution does not exist")

In [ ]:
# If there is no x such that Ax = y, can we find x such that Ax is close to y?
# The closest is given by least squares

x = linalg.lstsq(A, y, rcond=None)[0]
print("The best solution: ", x)
print("The closest we can get: ", A @ x)